Init back
utfpr/ppgcc-cm-datacapes-back pull request #3
Opened 2022-03-16 19:48 UTC by als-v

2022-03-22 00:49 UTC, JuanFSR reviewed
Good job!

2022-03-23 12:50 UTC, caiotheodoro reviewed
dale

2022-03-23 19:28 UTC, dennisurtubia commented on package.json
> +    "yarn": "^1.22.17"
Removes `yarn` dependency. We can use `npm`.

2022-03-23 19:29 UTC, dennisurtubia requested changes

2022-03-23 19:29 UTC, dennisurtubia commented on .gitignore
> +*.lock
We need to version the `lock` file.

2022-03-23 19:50 UTC, merged